package rocks.lecomte.solver.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName="Solver")
@NoArgsConstructor
public class AutoGeneratedKey {
    private String id;
    private String payload;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute(attributeName="request")
    public String getRequest() { return this.payload; }
    public void setRequest(String payload) { this.payload = payload; }

}